---
- hosts: dockerhost

  tasks:
  - name: Stop Container
    command: docker stop regapp-server
    ignore_errors: yes

  - name: remove the container
    command: docker rm regapp-server
    ignore_errors: yes

  - name: remove image
    command: docker rmi habeeba001/dead:latest
    ignore_errors: yes

  - name: create container
    command: docker run -d --name regapp-server -p 9000:8080 habeeba001/dead:latest

